version: "3.8"

services:
  flaskapp:
    build: .

    ports: 
    - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: src/app.py
      FLASK_RUN_HOST: 0.0.0.0
    depends_on: 
      - mysql

    
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: appointmentapp
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:   
      - type: bind
        source: C:\Users\yohan\Documents\pnc\contenedores\MedicalGoFlask\appointmentapp.sql
        target:  /docker-entrypoint-initdb.d/appointmentapp.sql
      - type: volume
        source: medicalgo_vol
        target: /var/lib/mysql
    
volumes:
    medicalgo_vol:
